### ISSUE TITLE
Not working with rails 5

### ISSUE THREAD

**Issue by anthonymidili** [torbjon/octicons-rails#5]
I recently updated to rails 5.0.0 and have not been able to get octicons-rails gem to bundle.
Getting this error...

`Bundler could not find compatible versions for gem "railties":
  In Gemfile`
`octicons-rails was resolved to 2.0.2.1, which depends on
      railties (< 5.0, >= 3.2)`

**Comment by zedtux** [comment]
@torbjon when will this gem be updated?
